UPDATE entreprise SET departement='Ain', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '01%';
UPDATE entreprise SET departement='Aisne', region='Hauts-de-France' WHERE code_postal LIKE '02%';
UPDATE entreprise SET departement='Allier', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '03%';
UPDATE entreprise SET departement='Alpes-de-Haute-Provence', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '04%';
UPDATE entreprise SET departement='Alpes-de-Haute-Provence', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '04%';
UPDATE entreprise SET departement='Hautes-Alpes', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '05%';
UPDATE entreprise SET departement='Alpes-Maritimes', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '06%';
UPDATE entreprise SET departement='Ardèche', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '07%';
UPDATE entreprise SET departement='Ardennes', region='Grand Est' WHERE code_postal LIKE '08%';
UPDATE entreprise SET departement='Ariège', region='Occitanie' WHERE code_postal LIKE '09%';
UPDATE entreprise SET departement='Aube', region='Grand Est' WHERE code_postal LIKE '10%';
UPDATE entreprise SET departement='Aude', region='Occitanie' WHERE code_postal LIKE '11%';
UPDATE entreprise SET departement='Aveyron', region='Occitanie' WHERE code_postal LIKE '12%';
UPDATE entreprise SET departement='Bouches-du-Rhône', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '13%';
UPDATE entreprise SET departement='Calvados', region='Normandie' WHERE code_postal LIKE '14%';
UPDATE entreprise SET departement='Cantal', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '15%';
UPDATE entreprise SET departement='Charente', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '16%';
UPDATE entreprise SET departement='Charente-Maritime', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '17%';
UPDATE entreprise SET departement='Cher', region='Centre-Val de Loire' WHERE code_postal LIKE '18%';
UPDATE entreprise SET departement='Corrèze', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '19%';
UPDATE entreprise SET departement='Corse-du-Sud', region='Corse' WHERE code_postal LIKE '200%' OR code_postal LIKE '201%';
UPDATE entreprise SET departement='Haute-Corse', region='Corse' WHERE code_postal LIKE '202%' OR code_postal LIKE '206%';
UPDATE entreprise SET departement='Côte-d''Or', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '21%';
UPDATE entreprise SET departement='Côtes-d''Armor', region='Bretagne' WHERE code_postal LIKE '22%';
UPDATE entreprise SET departement='Creuse', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '23%';
UPDATE entreprise SET departement='Dordogne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '24%';
UPDATE entreprise SET departement='Doubs', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '25%';
UPDATE entreprise SET departement='Drôme', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '26%';
UPDATE entreprise SET departement='Eure', region='Normandie' WHERE code_postal LIKE '27%';
UPDATE entreprise SET departement='Eure-et-Loir', region='Centre-Val de Loire' WHERE code_postal LIKE '28%';
UPDATE entreprise SET departement='Finistère', region='Bretagne' WHERE code_postal LIKE '29%';
UPDATE entreprise SET departement='Gard', region='Occitanie' WHERE code_postal LIKE '30%';
UPDATE entreprise SET departement='Haute-Garonne', region='Occitanie' WHERE code_postal LIKE '31%';
UPDATE entreprise SET departement='Gers', region='Occitanie' WHERE code_postal LIKE '32%';
UPDATE entreprise SET departement='Gironde', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '33%';
UPDATE entreprise SET departement='Hérault', region='Occitanie' WHERE code_postal LIKE '34%';
UPDATE entreprise SET departement='Ille-et-Vilaine', region='Bretagne' WHERE code_postal LIKE '35%';
UPDATE entreprise SET departement='Indre', region='Centre-Val de Loire' WHERE code_postal LIKE '36%';
UPDATE entreprise SET departement='Indre-et-Loire', region='Centre-Val de Loire' WHERE code_postal LIKE '37%';
UPDATE entreprise SET departement='Isère', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '38%';
UPDATE entreprise SET departement='Jura', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '39%';
UPDATE entreprise SET departement='Landes', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '40%';
UPDATE entreprise SET departement='Loir-et-Cher', region='Centre-Val de Loire' WHERE code_postal LIKE '41%';
UPDATE entreprise SET departement='Loire', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '42%';
UPDATE entreprise SET departement='Haute-Loire', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '43%';
UPDATE entreprise SET departement='Loire-Atlantique', region='Pays de la Loire' WHERE code_postal LIKE '44%';
UPDATE entreprise SET departement='Loiret', region='Centre-Val de Loire' WHERE code_postal LIKE '45%';
UPDATE entreprise SET departement='Lot', region='Occitanie' WHERE code_postal LIKE '46%';
UPDATE entreprise SET departement='Lot-et-Garonne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '47%';
UPDATE entreprise SET departement='Lozère', region='Occitanie' WHERE code_postal LIKE '48%';
UPDATE entreprise SET departement='Maine-et-Loire', region='Pays de la Loire' WHERE code_postal LIKE '49%';
UPDATE entreprise SET departement='Manche', region='Normandie' WHERE code_postal LIKE '50%';
UPDATE entreprise SET departement='Marne', region='Grand Est' WHERE code_postal LIKE '51%';
UPDATE entreprise SET departement='Haute-Marne', region='Grand Est' WHERE code_postal LIKE '52%';
UPDATE entreprise SET departement='Mayenne', region='Pays de la Loire' WHERE code_postal LIKE '53%';
UPDATE entreprise SET departement='Meurthe-et-Moselle', region='Grand Est' WHERE code_postal LIKE '54%';
UPDATE entreprise SET departement='Meuse', region='Grand Est' WHERE code_postal LIKE '55%';
UPDATE entreprise SET departement='Morbihan', region='Bretagne' WHERE code_postal LIKE '56%';
UPDATE entreprise SET departement='Moselle', region='Grand Est' WHERE code_postal LIKE '57%';
UPDATE entreprise SET departement='Nièvre', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '58%';
UPDATE entreprise SET departement='Nord', region='Hauts-de-France' WHERE code_postal LIKE '59%';
UPDATE entreprise SET departement='Oise', region='Hauts-de-France' WHERE code_postal LIKE '60%';
UPDATE entreprise SET departement='Orne', region='Normandie' WHERE code_postal LIKE '61%';
UPDATE entreprise SET departement='Pas-de-Calais', region='Hauts-de-France' WHERE code_postal LIKE '62%';
UPDATE entreprise SET departement='Puy-de-Dôme', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '63%';
UPDATE entreprise SET departement='Pyrénées-Atlantiques', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '64%';
UPDATE entreprise SET departement='Hautes-Pyrénées', region='Occitanie' WHERE code_postal LIKE '65%';
UPDATE entreprise SET departement='Pyrénées-Orientales', region='Occitanie' WHERE code_postal LIKE '66%';
UPDATE entreprise SET departement='Bas-Rhin', region='Grand Est' WHERE code_postal LIKE '67%';
UPDATE entreprise SET departement='Haut-Rhin', region='Grand Est' WHERE code_postal LIKE '68%';
UPDATE entreprise SET departement='Rhône', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '69%';
UPDATE entreprise SET departement='Haute-Saône', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '70%';
UPDATE entreprise SET departement='Saône-et-Loire', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '71%';
UPDATE entreprise SET departement='Sarthe', region='Pays de la Loire' WHERE code_postal LIKE '72%';
UPDATE entreprise SET departement='Savoie', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '73%';
UPDATE entreprise SET departement='Haute-Savoie', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '74%';
UPDATE entreprise SET departement='Paris', region='Île-de-France' WHERE code_postal LIKE '75%';
UPDATE entreprise SET departement='Seine-Maritime', region='Normandie' WHERE code_postal LIKE '76%';
UPDATE entreprise SET departement='Seine-et-Marne', region='Île-de-France' WHERE code_postal LIKE '77%';
UPDATE entreprise SET departement='Yvelines', region='Île-de-France' WHERE code_postal LIKE '78%';
UPDATE entreprise SET departement='Deux-Sèvres', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '79%';
UPDATE entreprise SET departement='Somme', region='Hauts-de-France' WHERE code_postal LIKE '80%';
UPDATE entreprise SET departement='Tarn', region='Occitanie' WHERE code_postal LIKE '81%';
UPDATE entreprise SET departement='Tarn-et-Garonne', region='Occitanie' WHERE code_postal LIKE '82%';
UPDATE entreprise SET departement='Var', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '83%';
UPDATE entreprise SET departement='Vaucluse', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '84%';
UPDATE entreprise SET departement='Vendée', region='Pays de la Loire' WHERE code_postal LIKE '85%';
UPDATE entreprise SET departement='Vienne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '86%';
UPDATE entreprise SET departement='Haute-Vienne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '87%';
UPDATE entreprise SET departement='Vosges', region='Grand Est' WHERE code_postal LIKE '88%';
UPDATE entreprise SET departement='Yonne', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '89%';
UPDATE entreprise SET departement='Territoire de Belfort', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '90%';
UPDATE entreprise SET departement='Essonne', region='Île-de-France' WHERE code_postal LIKE '91%';
UPDATE entreprise SET departement='Hauts-de-Seine', region='Île-de-France' WHERE code_postal LIKE '92%';
UPDATE entreprise SET departement='Seine-Saint-Denis', region='Île-de-France' WHERE code_postal LIKE '93%';
UPDATE entreprise SET departement='Val-de-Marne', region='Île-de-France' WHERE code_postal LIKE '94%';
UPDATE entreprise SET departement='Val-d''Oise', region='Île-de-France' WHERE code_postal LIKE '95%';
UPDATE entreprise SET departement='Guadeloupe', region='Guadeloupe' WHERE code_postal LIKE '971%';
UPDATE entreprise SET departement='Martinique', region='Martinique' WHERE code_postal LIKE '972%';
UPDATE entreprise SET departement='Guyane', region='Guyane' WHERE code_postal LIKE '973%';
UPDATE entreprise SET departement='La Réunion', region='La Réunion' WHERE code_postal LIKE '974%';
UPDATE entreprise SET departement='Mayotte', region='Mayotte' WHERE code_postal LIKE '976%';
