UPDATE etablissement SET departement='Ain', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '01%';
UPDATE etablissement SET departement='Aisne', region='Hauts-de-France' WHERE code_postal LIKE '02%';
UPDATE etablissement SET departement='Allier', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '03%';
UPDATE etablissement SET departement='Alpes-de-Haute-Provence', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '04%';
UPDATE etablissement SET departement='Alpes-de-Haute-Provence', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '04%';
UPDATE etablissement SET departement='Hautes-Alpes', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '05%';
UPDATE etablissement SET departement='Alpes-Maritimes', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '06%';
UPDATE etablissement SET departement='Ardèche', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '07%';
UPDATE etablissement SET departement='Ardennes', region='Grand Est' WHERE code_postal LIKE '08%';
UPDATE etablissement SET departement='Ariège', region='Occitanie' WHERE code_postal LIKE '09%';
UPDATE etablissement SET departement='Aube', region='Grand Est' WHERE code_postal LIKE '10%';
UPDATE etablissement SET departement='Aude', region='Occitanie' WHERE code_postal LIKE '11%';
UPDATE etablissement SET departement='Aveyron', region='Occitanie' WHERE code_postal LIKE '12%';
UPDATE etablissement SET departement='Bouches-du-Rhône', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '13%';
UPDATE etablissement SET departement='Calvados', region='Normandie' WHERE code_postal LIKE '14%';
UPDATE etablissement SET departement='Cantal', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '15%';
UPDATE etablissement SET departement='Charente', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '16%';
UPDATE etablissement SET departement='Charente-Maritime', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '17%';
UPDATE etablissement SET departement='Cher', region='Centre-Val de Loire' WHERE code_postal LIKE '18%';
UPDATE etablissement SET departement='Corrèze', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '19%';
UPDATE etablissement SET departement='Corse-du-Sud', region='Corse' WHERE code_postal LIKE '200%' OR code_postal LIKE '201%';
UPDATE etablissement SET departement='Haute-Corse', region='Corse' WHERE code_postal LIKE '202%' OR code_postal LIKE '206%';
UPDATE etablissement SET departement='Côte-d''Or', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '21%';
UPDATE etablissement SET departement='Côtes-d''Armor', region='Bretagne' WHERE code_postal LIKE '22%';
UPDATE etablissement SET departement='Creuse', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '23%';
UPDATE etablissement SET departement='Dordogne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '24%';
UPDATE etablissement SET departement='Doubs', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '25%';
UPDATE etablissement SET departement='Drôme', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '26%';
UPDATE etablissement SET departement='Eure', region='Normandie' WHERE code_postal LIKE '27%';
UPDATE etablissement SET departement='Eure-et-Loir', region='Centre-Val de Loire' WHERE code_postal LIKE '28%';
UPDATE etablissement SET departement='Finistère', region='Bretagne' WHERE code_postal LIKE '29%';
UPDATE etablissement SET departement='Gard', region='Occitanie' WHERE code_postal LIKE '30%';
UPDATE etablissement SET departement='Haute-Garonne', region='Occitanie' WHERE code_postal LIKE '31%';
UPDATE etablissement SET departement='Gers', region='Occitanie' WHERE code_postal LIKE '32%';
UPDATE etablissement SET departement='Gironde', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '33%';
UPDATE etablissement SET departement='Hérault', region='Occitanie' WHERE code_postal LIKE '34%';
UPDATE etablissement SET departement='Ille-et-Vilaine', region='Bretagne' WHERE code_postal LIKE '35%';
UPDATE etablissement SET departement='Indre', region='Centre-Val de Loire' WHERE code_postal LIKE '36%';
UPDATE etablissement SET departement='Indre-et-Loire', region='Centre-Val de Loire' WHERE code_postal LIKE '37%';
UPDATE etablissement SET departement='Isère', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '38%';
UPDATE etablissement SET departement='Jura', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '39%';
UPDATE etablissement SET departement='Landes', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '40%';
UPDATE etablissement SET departement='Loir-et-Cher', region='Centre-Val de Loire' WHERE code_postal LIKE '41%';
UPDATE etablissement SET departement='Loire', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '42%';
UPDATE etablissement SET departement='Haute-Loire', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '43%';
UPDATE etablissement SET departement='Loire-Atlantique', region='Pays de la Loire' WHERE code_postal LIKE '44%';
UPDATE etablissement SET departement='Loiret', region='Centre-Val de Loire' WHERE code_postal LIKE '45%';
UPDATE etablissement SET departement='Lot', region='Occitanie' WHERE code_postal LIKE '46%';
UPDATE etablissement SET departement='Lot-et-Garonne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '47%';
UPDATE etablissement SET departement='Lozère', region='Occitanie' WHERE code_postal LIKE '48%';
UPDATE etablissement SET departement='Maine-et-Loire', region='Pays de la Loire' WHERE code_postal LIKE '49%';
UPDATE etablissement SET departement='Manche', region='Normandie' WHERE code_postal LIKE '50%';
UPDATE etablissement SET departement='Marne', region='Grand Est' WHERE code_postal LIKE '51%';
UPDATE etablissement SET departement='Haute-Marne', region='Grand Est' WHERE code_postal LIKE '52%';
UPDATE etablissement SET departement='Mayenne', region='Pays de la Loire' WHERE code_postal LIKE '53%';
UPDATE etablissement SET departement='Meurthe-et-Moselle', region='Grand Est' WHERE code_postal LIKE '54%';
UPDATE etablissement SET departement='Meuse', region='Grand Est' WHERE code_postal LIKE '55%';
UPDATE etablissement SET departement='Morbihan', region='Bretagne' WHERE code_postal LIKE '56%';
UPDATE etablissement SET departement='Moselle', region='Grand Est' WHERE code_postal LIKE '57%';
UPDATE etablissement SET departement='Nièvre', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '58%';
UPDATE etablissement SET departement='Nord', region='Hauts-de-France' WHERE code_postal LIKE '59%';
UPDATE etablissement SET departement='Oise', region='Hauts-de-France' WHERE code_postal LIKE '60%';
UPDATE etablissement SET departement='Orne', region='Normandie' WHERE code_postal LIKE '61%';
UPDATE etablissement SET departement='Pas-de-Calais', region='Hauts-de-France' WHERE code_postal LIKE '62%';
UPDATE etablissement SET departement='Puy-de-Dôme', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '63%';
UPDATE etablissement SET departement='Pyrénées-Atlantiques', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '64%';
UPDATE etablissement SET departement='Hautes-Pyrénées', region='Occitanie' WHERE code_postal LIKE '65%';
UPDATE etablissement SET departement='Pyrénées-Orientales', region='Occitanie' WHERE code_postal LIKE '66%';
UPDATE etablissement SET departement='Bas-Rhin', region='Grand Est' WHERE code_postal LIKE '67%';
UPDATE etablissement SET departement='Haut-Rhin', region='Grand Est' WHERE code_postal LIKE '68%';
UPDATE etablissement SET departement='Rhône', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '69%';
UPDATE etablissement SET departement='Haute-Saône', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '70%';
UPDATE etablissement SET departement='Saône-et-Loire', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '71%';
UPDATE etablissement SET departement='Sarthe', region='Pays de la Loire' WHERE code_postal LIKE '72%';
UPDATE etablissement SET departement='Savoie', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '73%';
UPDATE etablissement SET departement='Haute-Savoie', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '74%';
UPDATE etablissement SET departement='Paris', region='Île-de-France' WHERE code_postal LIKE '75%';
UPDATE etablissement SET departement='Seine-Maritime', region='Normandie' WHERE code_postal LIKE '76%';
UPDATE etablissement SET departement='Seine-et-Marne', region='Île-de-France' WHERE code_postal LIKE '77%';
UPDATE etablissement SET departement='Yvelines', region='Île-de-France' WHERE code_postal LIKE '78%';
UPDATE etablissement SET departement='Deux-Sèvres', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '79%';
UPDATE etablissement SET departement='Somme', region='Hauts-de-France' WHERE code_postal LIKE '80%';
UPDATE etablissement SET departement='Tarn', region='Occitanie' WHERE code_postal LIKE '81%';
UPDATE etablissement SET departement='Tarn-et-Garonne', region='Occitanie' WHERE code_postal LIKE '82%';
UPDATE etablissement SET departement='Var', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '83%';
UPDATE etablissement SET departement='Vaucluse', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '84%';
UPDATE etablissement SET departement='Vendée', region='Pays de la Loire' WHERE code_postal LIKE '85%';
UPDATE etablissement SET departement='Vienne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '86%';
UPDATE etablissement SET departement='Haute-Vienne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '87%';
UPDATE etablissement SET departement='Vosges', region='Grand Est' WHERE code_postal LIKE '88%';
UPDATE etablissement SET departement='Yonne', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '89%';
UPDATE etablissement SET departement='Territoire de Belfort', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '90%';
UPDATE etablissement SET departement='Essonne', region='Île-de-France' WHERE code_postal LIKE '91%';
UPDATE etablissement SET departement='Hauts-de-Seine', region='Île-de-France' WHERE code_postal LIKE '92%';
UPDATE etablissement SET departement='Seine-Saint-Denis', region='Île-de-France' WHERE code_postal LIKE '93%';
UPDATE etablissement SET departement='Val-de-Marne', region='Île-de-France' WHERE code_postal LIKE '94%';
UPDATE etablissement SET departement='Val-d''Oise', region='Île-de-France' WHERE code_postal LIKE '95%';
UPDATE etablissement SET departement='Guadeloupe', region='Guadeloupe' WHERE code_postal LIKE '971%';
UPDATE etablissement SET departement='Martinique', region='Martinique' WHERE code_postal LIKE '972%';
UPDATE etablissement SET departement='Guyane', region='Guyane' WHERE code_postal LIKE '973%';
UPDATE etablissement SET departement='La Réunion', region='La Réunion' WHERE code_postal LIKE '974%';
UPDATE etablissement SET departement='Mayotte', region='Mayotte' WHERE code_postal LIKE '976%';
