UPDATE contact SET departement='Ain', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '01%';
UPDATE contact SET departement='Aisne', region='Hauts-de-France' WHERE code_postal LIKE '02%';
UPDATE contact SET departement='Allier', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '03%';
UPDATE contact SET departement='Alpes-de-Haute-Provence', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '04%';
UPDATE contact SET departement='Alpes-de-Haute-Provence', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '04%';
UPDATE contact SET departement='Hautes-Alpes', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '05%';
UPDATE contact SET departement='Alpes-Maritimes', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '06%';
UPDATE contact SET departement='Ardèche', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '07%';
UPDATE contact SET departement='Ardennes', region='Grand Est' WHERE code_postal LIKE '08%';
UPDATE contact SET departement='Ariège', region='Occitanie' WHERE code_postal LIKE '09%';
UPDATE contact SET departement='Aube', region='Grand Est' WHERE code_postal LIKE '10%';
UPDATE contact SET departement='Aude', region='Occitanie' WHERE code_postal LIKE '11%';
UPDATE contact SET departement='Aveyron', region='Occitanie' WHERE code_postal LIKE '12%';
UPDATE contact SET departement='Bouches-du-Rhône', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '13%';
UPDATE contact SET departement='Calvados', region='Normandie' WHERE code_postal LIKE '14%';
UPDATE contact SET departement='Cantal', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '15%';
UPDATE contact SET departement='Charente', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '16%';
UPDATE contact SET departement='Charente-Maritime', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '17%';
UPDATE contact SET departement='Cher', region='Centre-Val de Loire' WHERE code_postal LIKE '18%';
UPDATE contact SET departement='Corrèze', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '19%';
UPDATE contact SET departement='Corse-du-Sud', region='Corse' WHERE code_postal LIKE '200%' OR code_postal LIKE '201%';
UPDATE contact SET departement='Haute-Corse', region='Corse' WHERE code_postal LIKE '202%' OR code_postal LIKE '206%';
UPDATE contact SET departement='Côte-d''Or', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '21%';
UPDATE contact SET departement='Côtes-d''Armor', region='Bretagne' WHERE code_postal LIKE '22%';
UPDATE contact SET departement='Creuse', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '23%';
UPDATE contact SET departement='Dordogne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '24%';
UPDATE contact SET departement='Doubs', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '25%';
UPDATE contact SET departement='Drôme', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '26%';
UPDATE contact SET departement='Eure', region='Normandie' WHERE code_postal LIKE '27%';
UPDATE contact SET departement='Eure-et-Loir', region='Centre-Val de Loire' WHERE code_postal LIKE '28%';
UPDATE contact SET departement='Finistère', region='Bretagne' WHERE code_postal LIKE '29%';
UPDATE contact SET departement='Gard', region='Occitanie' WHERE code_postal LIKE '30%';
UPDATE contact SET departement='Haute-Garonne', region='Occitanie' WHERE code_postal LIKE '31%';
UPDATE contact SET departement='Gers', region='Occitanie' WHERE code_postal LIKE '32%';
UPDATE contact SET departement='Gironde', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '33%';
UPDATE contact SET departement='Hérault', region='Occitanie' WHERE code_postal LIKE '34%';
UPDATE contact SET departement='Ille-et-Vilaine', region='Bretagne' WHERE code_postal LIKE '35%';
UPDATE contact SET departement='Indre', region='Centre-Val de Loire' WHERE code_postal LIKE '36%';
UPDATE contact SET departement='Indre-et-Loire', region='Centre-Val de Loire' WHERE code_postal LIKE '37%';
UPDATE contact SET departement='Isère', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '38%';
UPDATE contact SET departement='Jura', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '39%';
UPDATE contact SET departement='Landes', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '40%';
UPDATE contact SET departement='Loir-et-Cher', region='Centre-Val de Loire' WHERE code_postal LIKE '41%';
UPDATE contact SET departement='Loire', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '42%';
UPDATE contact SET departement='Haute-Loire', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '43%';
UPDATE contact SET departement='Loire-Atlantique', region='Pays de la Loire' WHERE code_postal LIKE '44%';
UPDATE contact SET departement='Loiret', region='Centre-Val de Loire' WHERE code_postal LIKE '45%';
UPDATE contact SET departement='Lot', region='Occitanie' WHERE code_postal LIKE '46%';
UPDATE contact SET departement='Lot-et-Garonne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '47%';
UPDATE contact SET departement='Lozère', region='Occitanie' WHERE code_postal LIKE '48%';
UPDATE contact SET departement='Maine-et-Loire', region='Pays de la Loire' WHERE code_postal LIKE '49%';
UPDATE contact SET departement='Manche', region='Normandie' WHERE code_postal LIKE '50%';
UPDATE contact SET departement='Marne', region='Grand Est' WHERE code_postal LIKE '51%';
UPDATE contact SET departement='Haute-Marne', region='Grand Est' WHERE code_postal LIKE '52%';
UPDATE contact SET departement='Mayenne', region='Pays de la Loire' WHERE code_postal LIKE '53%';
UPDATE contact SET departement='Meurthe-et-Moselle', region='Grand Est' WHERE code_postal LIKE '54%';
UPDATE contact SET departement='Meuse', region='Grand Est' WHERE code_postal LIKE '55%';
UPDATE contact SET departement='Morbihan', region='Bretagne' WHERE code_postal LIKE '56%';
UPDATE contact SET departement='Moselle', region='Grand Est' WHERE code_postal LIKE '57%';
UPDATE contact SET departement='Nièvre', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '58%';
UPDATE contact SET departement='Nord', region='Hauts-de-France' WHERE code_postal LIKE '59%';
UPDATE contact SET departement='Oise', region='Hauts-de-France' WHERE code_postal LIKE '60%';
UPDATE contact SET departement='Orne', region='Normandie' WHERE code_postal LIKE '61%';
UPDATE contact SET departement='Pas-de-Calais', region='Hauts-de-France' WHERE code_postal LIKE '62%';
UPDATE contact SET departement='Puy-de-Dôme', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '63%';
UPDATE contact SET departement='Pyrénées-Atlantiques', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '64%';
UPDATE contact SET departement='Hautes-Pyrénées', region='Occitanie' WHERE code_postal LIKE '65%';
UPDATE contact SET departement='Pyrénées-Orientales', region='Occitanie' WHERE code_postal LIKE '66%';
UPDATE contact SET departement='Bas-Rhin', region='Grand Est' WHERE code_postal LIKE '67%';
UPDATE contact SET departement='Haut-Rhin', region='Grand Est' WHERE code_postal LIKE '68%';
UPDATE contact SET departement='Rhône', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '69%';
UPDATE contact SET departement='Haute-Saône', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '70%';
UPDATE contact SET departement='Saône-et-Loire', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '71%';
UPDATE contact SET departement='Sarthe', region='Pays de la Loire' WHERE code_postal LIKE '72%';
UPDATE contact SET departement='Savoie', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '73%';
UPDATE contact SET departement='Haute-Savoie', region='Auvergne-Rhône-Alpes' WHERE code_postal LIKE '74%';
UPDATE contact SET departement='Paris', region='Île-de-France' WHERE code_postal LIKE '75%';
UPDATE contact SET departement='Seine-Maritime', region='Normandie' WHERE code_postal LIKE '76%';
UPDATE contact SET departement='Seine-et-Marne', region='Île-de-France' WHERE code_postal LIKE '77%';
UPDATE contact SET departement='Yvelines', region='Île-de-France' WHERE code_postal LIKE '78%';
UPDATE contact SET departement='Deux-Sèvres', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '79%';
UPDATE contact SET departement='Somme', region='Hauts-de-France' WHERE code_postal LIKE '80%';
UPDATE contact SET departement='Tarn', region='Occitanie' WHERE code_postal LIKE '81%';
UPDATE contact SET departement='Tarn-et-Garonne', region='Occitanie' WHERE code_postal LIKE '82%';
UPDATE contact SET departement='Var', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '83%';
UPDATE contact SET departement='Vaucluse', region='Provence-Alpes-Côte d''Azur' WHERE code_postal LIKE '84%';
UPDATE contact SET departement='Vendée', region='Pays de la Loire' WHERE code_postal LIKE '85%';
UPDATE contact SET departement='Vienne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '86%';
UPDATE contact SET departement='Haute-Vienne', region='Nouvelle-Aquitaine' WHERE code_postal LIKE '87%';
UPDATE contact SET departement='Vosges', region='Grand Est' WHERE code_postal LIKE '88%';
UPDATE contact SET departement='Yonne', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '89%';
UPDATE contact SET departement='Territoire de Belfort', region='Bourgogne-Franche-Comté' WHERE code_postal LIKE '90%';
UPDATE contact SET departement='Essonne', region='Île-de-France' WHERE code_postal LIKE '91%';
UPDATE contact SET departement='Hauts-de-Seine', region='Île-de-France' WHERE code_postal LIKE '92%';
UPDATE contact SET departement='Seine-Saint-Denis', region='Île-de-France' WHERE code_postal LIKE '93%';
UPDATE contact SET departement='Val-de-Marne', region='Île-de-France' WHERE code_postal LIKE '94%';
UPDATE contact SET departement='Val-d''Oise', region='Île-de-France' WHERE code_postal LIKE '95%';
UPDATE contact SET departement='Guadeloupe', region='Guadeloupe' WHERE code_postal LIKE '971%';
UPDATE contact SET departement='Martinique', region='Martinique' WHERE code_postal LIKE '972%';
UPDATE contact SET departement='Guyane', region='Guyane' WHERE code_postal LIKE '973%';
UPDATE contact SET departement='La Réunion', region='La Réunion' WHERE code_postal LIKE '974%';
UPDATE contact SET departement='Mayotte', region='Mayotte' WHERE code_postal LIKE '976%';

