stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - main

build:
  stage: build
  before_script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - rm -rf ~/.ssh/known_hosts
    - ssh-keyscan -H '10.24.211.96' >> ~/.ssh/known_hosts
    - ssh-keyscan 10.24.211.96 | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh $SSH_HOST "sudo docker ps -a --filter "name=c2s-oc-front" -q | xargs sudo docker stop"
    - ssh $SSH_HOST "sudo docker ps -a --filter "name=c2s-oc-front" -q | xargs sudo docker rm"
    - ssh $SSH_HOST "sudo docker images --filter "reference=c2s-oc-front" -q | xargs sudo docker rmi"

  script:
    - scp -r build/* c2s-user@10.24.211.96:/opt/
    - ssh c2s-user@10.24.211.96 'cd /opt/ && npm install --production'
  only:
    - master
  environment:
    name: production
    url: http://yourproductionurl.com
