export const ocWelcomeAPIResponse = {
  messageAccueil: {
    id: 3,
    contenu: 'Bienvenu OC 2',
    groupe: 'ORGANISME_COMPLEMENTAIRE',
    dateCrea: '2023-06-30T11:03:16',
    dateMaj: '2023-06-30T11:03:16',
  },
  ressourceFiles: [
    {
      ressourceFichierId: 1,
      thematique: {
        ressourceThematiqueId: 1,
        titre: 'Rubrique OC 1',
        description: 'Description 1',
        groupe: 'ORGANISME_COMPLEMENTAIRE',
        ordre: 1,
        publique: false,
      },
      repertoire: '********',
      nom: 'Test_fichier_1',
      taille: 3455455,
      extension: 'pdf',
      dateCrea: '2021-01-30T11:03:16',
      dateMaj: '2021-02-28T11:03:16',
      type: 'PDF',
    },
    {
      ressourceFichierId: 3,
      thematique: {
        ressourceThematiqueId: 3,
        titre: 'Rubrique OC 2',
        description: 'Description 3',
        groupe: 'ORGANISME_COMPLEMENTAIRE',
        ordre: 3,
        publique: true,
      },
      repertoire: '********',
      nom: 'Test_fichier_3',
      taille: 3455999,
      extension: 'csv',
      dateCrea: '2021-03-30T11:03:16',
      dateMaj: '2021-04-30T11:03:16',
      type: 'EXCEL',
    },
    {
      ressourceFichierId: 5,
      thematique: {
        ressourceThematiqueId: 1,
        titre: 'Rubrique OC 1',
        description: 'Description 1',
        groupe: 'ORGANISME_COMPLEMENTAIRE',
        ordre: 1,
        publique: false,
      },
      repertoire: '********',
      nom: 'Test_fichier_5',
      taille: 4855455,
      extension: 'doc',
      dateCrea: '2021-05-30T11:03:16',
      dateMaj: '2021-06-30T11:03:16',
      type: 'WORD',
    },
    {
      ressourceFichierId: 7,
      thematique: {
        ressourceThematiqueId: 3,
        titre: 'Rubrique OC 2',
        description: 'Description 3',
        groupe: 'ORGANISME_COMPLEMENTAIRE',
        ordre: 3,
        publique: true,
      },
      repertoire: '********',
      nom: 'Test_fichier_7',
      taille: 3455455,
      extension: 'pdf',
      dateCrea: '2021-07-30T11:03:16',
      dateMaj: '2021-08-30T11:03:16',
      type: 'PDF',
    },
    {
      ressourceFichierId: 9,
      thematique: {
        ressourceThematiqueId: 1,
        titre: 'Rubrique OC 1',
        description: 'Description 1',
        groupe: 'ORGANISME_COMPLEMENTAIRE',
        ordre: 1,
        publique: false,
      },
      repertoire: '********',
      nom: 'Test_fichier_9',
      taille: 3455999,
      extension: 'xls',
      dateCrea: '2021-09-30T11:03:16',
      dateMaj: '2021-10-30T11:03:16',
      type: 'EXCEL',
    },
    {
      ressourceFichierId: 10,
      thematique: {
        ressourceThematiqueId: 1,
        titre: 'Rubrique OC 1',
        description: 'Description 1',
        groupe: 'ORGANISME_COMPLEMENTAIRE',
        ordre: 1,
        publique: false,
      },
      repertoire: '********',
      nom: 'Test_fichier_10',
      taille: 3455455,
      extension: 'pdf',
      dateCrea: '2021-10-30T11:03:16',
      dateMaj: '2021-11-30T11:03:16',
      type: 'PDF',
    },
    {
      ressourceFichierId: 12,
      thematique: {
        ressourceThematiqueId: 3,
        titre: 'Rubrique OC 2',
        description: 'Description 3',
        groupe: 'ORGANISME_COMPLEMENTAIRE',
        ordre: 3,
        publique: true,
      },
      repertoire: '********',
      nom: 'Test_fichier_13',
      taille: 3455999,
      extension: 'csv',
      dateCrea: '2022-01-30T11:03:16',
      dateMaj: '2022-01-30T11:03:16',
      type: 'EXCEL',
    },
  ],
};
