export const mockApiResponse = {
  list: [
    {
      id: 22,
      operationDate: '2024-09-18T13:36:24.201+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [MCRN - MUTUELLE CHEMINOTS NANTES]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 21,
      operationDate: '2024-09-18T13:36:24.197+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [MCRN - MUTUELLE CHEMINOTS NANTES]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 20,
      operationDate: '2024-09-18T13:35:13.305+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel:
        "Modification de l'OC [Mutuelle des anciens des chantiers de La Rochelle-Pallice]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 19,
      operationDate: '2024-09-18T13:35:13.303+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel:
        "Modification de l'OC [Mutuelle des anciens des chantiers de La Rochelle-Pallice]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 18,
      operationDate: '2024-09-18T13:35:06.571+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [Mutuelle Entrain]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 17,
      operationDate: '2024-09-18T13:35:06.567+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [Mutuelle Entrain]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 16,
      operationDate: '2024-09-18T13:35:00.902+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [Mutuelle Entrain]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 15,
      operationDate: '2024-09-18T13:35:00.899+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [Mutuelle Entrain]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 14,
      operationDate: '2024-09-18T13:34:55.756+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [ENTRENOUS Mutuelle]",
      membreId: 1,
      entrepriseNom: null,
    },
    {
      id: 13,
      operationDate: '2024-09-18T13:34:55.754+00:00',
      section: 'MODERATION_ETABLISSEMENTS',
      groupe: 'MODERATEUR',
      membreInformations: 'Test Modérateur',
      actionType: 'MODIFICATION',
      actionLabel: "Modification de l'OC [ENTRENOUS Mutuelle]",
      membreId: 1,
      entrepriseNom: null,
    },
  ],
  count: 22,
};
