FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy the built assets from local machine
COPY dist/ .

# Use the nginx config from volume mount
CMD ["nginx", "-g", "daemon off;"]
