#!/usr/bin/env bash

set -eou pipefail

SCRIPT_DIR=$(dirname -- "$0")

# --- Gitleaks precommit

$SCRIPT_DIR/gitleaks-detect-secrets.sh


# --- Front precommit

cd front
if [ -d "node_modules" ]; then
    yarn precommit
else
    echo "Skipping front precommit, yarn has not been run in front/ directory"
fi
