name: Install, build, lint and tests

on:
  push:
    branches: ['main', 'dev', 'mono-repo-dev']
  pull_request:
    branches: ['main', 'dev', 'mono-repo-dev']
defaults:
      run:
        working-directory: ./front

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: ./front/yarn.lock
          node-version: 18
      - name: Install packages
        run: yarn --immutable
      - name: Run the TS linter
        run: yarn lint
      - name: Run prettier
        run: yarn format:check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: ./front/yarn.lock
          node-version: 18
      - name: Install packages
        run: yarn --immutable
      - name: Run tests
        run: yarn test:coverage:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: ./front/yarn.lock
          node-version: 18
      - name: Install packages
        run: yarn --immutable
      - name: Run build
        run: yarn build
